# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('cuerpo', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
                'ordering': ['titulo'],
            },
        ),
    ]
