# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuntaDirectiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('sub_titulo', models.CharField(max_length=60, verbose_name='Periodo')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=60, verbose_name='Cargo de la persona')),
                ('foto', models.ImageField(upload_to='directiva', verbose_name='Fotografía')),
            ],
        ),
    ]
