# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_juntadirectiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('cuerpo', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Desarrollo',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='GestionAnterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField(verbose_name='Gestiones')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comunidad',
            options={'ordering': ['titulo'], 'verbose_name_plural': 'La Comunidad'},
        ),
        migrations.AlterModelOptions(
            name='juntadirectiva',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Junta Directiva'},
        ),
        migrations.RenameField(
            model_name='juntadirectiva',
            old_name='sub_titulo',
            new_name='periodo',
        ),
        migrations.RemoveField(
            model_name='juntadirectiva',
            name='titulo',
        ),
    ]
