# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180426_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestionanterior',
            options={'verbose_name_plural': 'Gestión Anterior'},
        ),
        migrations.AddField(
            model_name='comunidad',
            name='imagen',
            field=models.ImageField(default='/media/sayan.jpg', upload_to='comunidad', verbose_name='Imagen'),
        ),
    ]
